#!/usr/bin/env python3
"""Automatic generation of campaign documentation pages for all
tags with indices defined in the quest directory."""

from __future__ import annotations

import textwrap
from quest import Tag, PROJECT_ROOT


def generate_campaign_sections():
    tag_doc_dir = PROJECT_ROOT / "doc" / "guide" / "sections"

    for tag in Tag.list():
        with open(tag_doc_dir / f"campaign_{tag.name}.md", "w") as f:
            f.write(textwrap.dedent(f"""\
            <!-- autogenerated by guide build -->
            # {{{{ tag_title("{tag.name}") }}}}
            
            {{{{ tag_description("{tag.name}") }}}}
            
            ## Quests
            
            {{{{ tag_quests("{tag.name}") }}}}
            
            """))

def main():
    generate_campaign_sections()

if __name__ == '__main__':
    raise SystemExit(main())
