site_name: Proyecto SOL
site_description: Proyecto SOL
site_author: UAB::Programación_2
site_url: https://uab-p2.github.io/sol/
site_dir: html
docs_dir: sections

nav:
  - main():
      - Intro: index.md
  - quest():
      - Intro: campaigns.md
      - Despegue:
          - Intro: auto/campaign_despegue.md
          - Silicio y titanio(): auto/quest_silicio_y_titanio.md
          - Lógica lunática(): auto/quest_logica_lunatica.md
      - Objetos celestes:
          - Intro: auto/campaign_oop.md
          - Entre gatos(): auto/quest_entre_gatos.md
      - Recuerdos sintéticos:
          - Intro: auto/campaign_memory.md
          - Título del Quest(): auto/quest_placeholder.md
  - help():
      - Intro: codices.md

      - Primeros pasos:
          - codex/plataforma.md
          - codex/clone_project.md
          - codex/open_quest.md
          - codex/run_quest.md
          - codex/debugging.md


theme:
  name: material
  favicon: asset/img/white-balance-sunny.ico
  language: es

  icon:
    logo: material/white-balance-sunny

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/tune
        name: Light mode

    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/tune
        name: Dark mode

extra_css:
  - asset/css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - macros

extra:
  generator: false