site_name: Guía de estudio P2
site_description: Guía de estudio P2
site_author: Profesorado Programación 2, UAB

docs_dir: sections
site_dir: html

nav:
  - main(): index.md
  - quest():
      - Quests, campañas y calendario : campaigns.md
      - Despegue : auto/campaign_despegue.md
      - Objetos celestes: auto/campaign_oop.md
      - Recuerdos sintéticos: auto/campaign_memory.md
  - help():
      - Intro : codices.md
      - Sintaxis : codex_oop_syntax.md
      - Contenedores STL : codex_stl_usage.md

theme:
  name: material
  favicon: asset/white-balance-sunny.ico
  language: es

  icon:
    logo: material/white-balance-sunny

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/tune
        name: Light mode

    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/tune
        name: Dark mode

extra_css:
  - css/extra.css

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - macros

extra:
  generator: false